services:
  supernode:
    image: flwr/supernode:1.23.0
    command: ["--insecure", "--isolation", "process", "--superlink", "superlink:9092", "--node-config", "executor-image=\"zk0:latest\" dataset-uri=\"${DATASET_URI}\"", "--clientappio-api-address", "0.0.0.0:8080"]
    ports:
      - "8080"
    environment:
      - DATASET_URI
    volumes:
      - ../pyproject.toml:/workspace/pyproject.toml:ro
      - ../outputs:/workspace/outputs
    networks:
      - flwr-network

networks:
  flwr-network:
    external: true