services:
  supernode:
    image: flwr/supernode:1.23.0
    command: ["--insecure", "--isolation", "process", "--superlink", "superlink:9092", "--node-config", "dataset-uri = ${DATASET_URI}", "--clientappio-api-address", "0.0.0.0:8080"]
    ports:
      - "8080"
    environment:
      - DATASET_URI
    networks:
      - flwr-network

  superexec-client:
    build:
      context: .
      dockerfile: docker/superexec.Dockerfile
    image: zk0-superexec:v0.7.0
    command: ["--insecure", "--plugin-type", "clientapp", "--appio-api-address", "supernode:8080"]
    volumes:
      - ./outputs:/app/outputs
      - ./pyproject.toml:/app/pyproject.toml
    depends_on:
      - supernode
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - flwr-network

networks:
  flwr-network:
    external: true